spring:
  application:
    name: ai-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ai
    driver-class-name: org.postgresql.Driver
    username: ai_service
    password: ai
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always
      prometheus:
        enabled: true
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /ai/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
server:
  port: 19094

spartaLogistics:
  ai:
    url:  https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent
    api-key: AIzaSyAKf6QSyctaj_gDQxzo4CfSRGJMt4Ckgys